// AUTO-GENERATED by scripts/generate_blueprints.py — do not edit.

export interface BlueprintBuilding {
  ref: string;
  name: string;
  pages: number[];
}

export const BLUEPRINTS: Record<string, BlueprintBuilding[]> = {
  "relation/2806804": [
    {
      ref: "35",
      name: "Robert E. Kennedy Library",
      pages: [
        require("../../assets/blueprints/35/page-1.webp"),
        require("../../assets/blueprints/35/page-2.webp"),
        require("../../assets/blueprints/35/page-3.webp"),
        require("../../assets/blueprints/35/page-4.webp"),
        require("../../assets/blueprints/35/page-5.webp"),
      ],
    },
  ],
  "relation/4504112": [
    {
      ref: "13",
      name: "Engineering",
      pages: [
        require("../../assets/blueprints/13/page-1.webp"),
        require("../../assets/blueprints/13/page-2.webp"),
      ],
    },
  ],
  "way/118003905": [
    {
      ref: "65",
      name: "Julian A. Mcphee University Union",
      pages: [
        require("../../assets/blueprints/65/page-1.webp"),
        require("../../assets/blueprints/65/page-2.webp"),
        require("../../assets/blueprints/65/page-3.webp"),
        require("../../assets/blueprints/65/page-4.webp"),
        require("../../assets/blueprints/65/page-5.webp"),
      ],
    },
  ],
  "way/1217465601": [
    {
      ref: "181",
      name: "William and Linda Frost Center for Research and Innovation",
      pages: [
        require("../../assets/blueprints/181/page-1.webp"),
        require("../../assets/blueprints/181/page-2.webp"),
        require("../../assets/blueprints/181/page-3.webp"),
        require("../../assets/blueprints/181/page-4.webp"),
        require("../../assets/blueprints/181/page-5.webp"),
      ],
    },
  ],
  "way/140213692": [
    {
      ref: "83",
      name: "Technology Park",
      pages: [
        require("../../assets/blueprints/83/page-1.webp"),
        require("../../assets/blueprints/83/page-2.webp"),
      ],
    },
  ],
  "way/160415341": [
    {
      ref: "2",
      name: "Cotchett Education Building",
      pages: [
        require("../../assets/blueprints/2/page-1.webp"),
        require("../../assets/blueprints/2/page-2.webp"),
        require("../../assets/blueprints/2/page-3.webp"),
      ],
    },
  ],
  "way/160415342": [
    {
      ref: "3",
      name: "Business",
      pages: [
        require("../../assets/blueprints/3/page-1.webp"),
        require("../../assets/blueprints/3/page-2.webp"),
        require("../../assets/blueprints/3/page-3.webp"),
        require("../../assets/blueprints/3/page-4.webp"),
      ],
    },
  ],
  "way/322170587": [
    {
      ref: "180",
      name: "Warren J. Baker Center for Science and Mathematics",
      pages: [
        require("../../assets/blueprints/180/page-1.webp"),
        require("../../assets/blueprints/180/page-2.webp"),
        require("../../assets/blueprints/180/page-3.webp"),
        require("../../assets/blueprints/180/page-4.webp"),
        require("../../assets/blueprints/180/page-5.webp"),
        require("../../assets/blueprints/180/page-6.webp"),
        require("../../assets/blueprints/180/page-7.webp"),
      ],
    },
  ],
  "way/323359887": [
    {
      ref: "47",
      name: "Faculty Offices North",
      pages: [
        require("../../assets/blueprints/47/page-1.webp"),
        require("../../assets/blueprints/47/page-2.webp"),
        require("../../assets/blueprints/47/page-3.webp"),
      ],
    },
  ],
  "way/323359888": [
    {
      ref: "47",
      name: "Faculty Offices North",
      pages: [
        require("../../assets/blueprints/47/page-1.webp"),
        require("../../assets/blueprints/47/page-2.webp"),
        require("../../assets/blueprints/47/page-3.webp"),
      ],
    },
  ],
  "way/38899881": [
    {
      ref: "192",
      name: "Engineering Iv",
      pages: [
        require("../../assets/blueprints/192/page-1.webp"),
        require("../../assets/blueprints/192/page-2.webp"),
        require("../../assets/blueprints/192/page-3.webp"),
      ],
    },
  ],
  "way/38899882": [
    {
      ref: "197",
      name: "Bonderson Engineering Projects Center",
      pages: [
        require("../../assets/blueprints/197/page-1.webp"),
        require("../../assets/blueprints/197/page-2.webp"),
      ],
    },
  ],
  "way/38899884": [
    {
      ref: "7",
      name: "Advanced Technology Laboratories",
      pages: [
        require("../../assets/blueprints/7/page-1.webp"),
      ],
    },
  ],
  "way/38939878": [
    {
      ref: "40",
      name: "Engineering South",
      pages: [
        require("../../assets/blueprints/40/page-1.webp"),
      ],
    },
  ],
  "way/38939879": [
    {
      ref: "26",
      name: "Graphic Arts",
      pages: [
        require("../../assets/blueprints/26/page-1.webp"),
        require("../../assets/blueprints/26/page-2.webp"),
        require("../../assets/blueprints/26/page-3.webp"),
        require("../../assets/blueprints/26/page-4.webp"),
      ],
    },
  ],
  "way/38939881": [
    {
      ref: "20",
      name: "Engineering East",
      pages: [
        require("../../assets/blueprints/20/page-1.webp"),
        require("../../assets/blueprints/20/page-2.webp"),
      ],
    },
  ],
  "way/38939883": [
    {
      ref: "14",
      name: "Frank E Pilling Building",
      pages: [
        require("../../assets/blueprints/14/page-1.webp"),
        require("../../assets/blueprints/14/page-2.webp"),
        require("../../assets/blueprints/14/page-3.webp"),
      ],
    },
  ],
  "way/38939884": [
    {
      ref: "13",
      name: "Engineering",
      pages: [
        require("../../assets/blueprints/13/page-1.webp"),
        require("../../assets/blueprints/13/page-2.webp"),
      ],
    },
    {
      ref: "21",
      name: "Engineering West",
      pages: [
        require("../../assets/blueprints/21/page-1.webp"),
        require("../../assets/blueprints/21/page-2.webp"),
        require("../../assets/blueprints/21/page-3.webp"),
        require("../../assets/blueprints/21/page-4.webp"),
        require("../../assets/blueprints/21/page-5.webp"),
        require("../../assets/blueprints/21/page-6.webp"),
      ],
    },
  ],
  "way/38939886": [
    {
      ref: "13",
      name: "Engineering",
      pages: [
        require("../../assets/blueprints/13/page-1.webp"),
        require("../../assets/blueprints/13/page-2.webp"),
      ],
    },
    {
      ref: "21",
      name: "Engineering West",
      pages: [
        require("../../assets/blueprints/21/page-1.webp"),
        require("../../assets/blueprints/21/page-2.webp"),
        require("../../assets/blueprints/21/page-3.webp"),
        require("../../assets/blueprints/21/page-4.webp"),
        require("../../assets/blueprints/21/page-5.webp"),
        require("../../assets/blueprints/21/page-6.webp"),
      ],
    },
  ],
  "way/38939888": [
    {
      ref: "34",
      name: "Walter F. Dexter Building",
      pages: [
        require("../../assets/blueprints/34/page-1.webp"),
        require("../../assets/blueprints/34/page-2.webp"),
      ],
    },
  ],
  "way/42335852": [
    {
      ref: "43",
      name: "Kinesiology",
      pages: [
        require("../../assets/blueprints/43/page-1.webp"),
        require("../../assets/blueprints/43/page-2.webp"),
        require("../../assets/blueprints/43/page-3.webp"),
        require("../../assets/blueprints/43/page-4.webp"),
        require("../../assets/blueprints/43/page-5.webp"),
      ],
    },
  ],
  "way/43738057": [
    {
      ref: "27",
      name: "Health Center",
      pages: [
        require("../../assets/blueprints/27/page-1.webp"),
        require("../../assets/blueprints/27/page-2.webp"),
      ],
    },
  ],
  "way/45599071": [
    {
      ref: "45",
      name: "H. P. Davidson Music Center",
      pages: [
        require("../../assets/blueprints/45/page-1.webp"),
        require("../../assets/blueprints/45/page-2.webp"),
        require("../../assets/blueprints/45/page-3.webp"),
      ],
    },
  ],
  "way/45600370": [
    {
      ref: "13",
      name: "Engineering",
      pages: [
        require("../../assets/blueprints/13/page-1.webp"),
        require("../../assets/blueprints/13/page-2.webp"),
      ],
    },
    {
      ref: "21",
      name: "Engineering West",
      pages: [
        require("../../assets/blueprints/21/page-1.webp"),
        require("../../assets/blueprints/21/page-2.webp"),
        require("../../assets/blueprints/21/page-3.webp"),
        require("../../assets/blueprints/21/page-4.webp"),
        require("../../assets/blueprints/21/page-5.webp"),
        require("../../assets/blueprints/21/page-6.webp"),
      ],
    },
  ],
  "way/45600373": [
    {
      ref: "46",
      name: "Old Natatorium",
      pages: [
        require("../../assets/blueprints/46/page-1.webp"),
        require("../../assets/blueprints/46/page-2.webp"),
        require("../../assets/blueprints/46/page-3.webp"),
      ],
    },
  ],
  "way/45600389": [
    {
      ref: "38",
      name: "Mathematics and Science",
      pages: [
        require("../../assets/blueprints/38/page-1.webp"),
        require("../../assets/blueprints/38/page-2.webp"),
      ],
    },
  ],
  "way/45600390": [
    {
      ref: "22",
      name: "English",
      pages: [
        require("../../assets/blueprints/22/page-1.webp"),
        require("../../assets/blueprints/22/page-2.webp"),
      ],
    },
    {
      ref: "10",
      name: "Alan A. Erhart Agriculture",
      pages: [
        require("../../assets/blueprints/10/page-1.webp"),
        require("../../assets/blueprints/10/page-2.webp"),
      ],
    },
  ],
  "way/45600394": [
    {
      ref: "19",
      name: "Dining Complex",
      pages: [
        require("../../assets/blueprints/19/page-1.webp"),
        require("../../assets/blueprints/19/page-2.webp"),
        require("../../assets/blueprints/19/page-3.webp"),
      ],
    },
  ],
  "way/45600395": [
    {
      ref: "44",
      name: "Alex and Fay Spanos Theatre",
      pages: [
        require("../../assets/blueprints/44/page-1.webp"),
        require("../../assets/blueprints/44/page-2.webp"),
        require("../../assets/blueprints/44/page-3.webp"),
      ],
    },
  ],
  "way/45600398": [
    {
      ref: "8",
      name: "Bioresource and Agricultural Engineering",
      pages: [
        require("../../assets/blueprints/8/page-1.webp"),
        require("../../assets/blueprints/8/page-2.webp"),
      ],
    },
  ],
  "way/45600403": [
    {
      ref: "1",
      name: "Administration",
      pages: [
        require("../../assets/blueprints/1/page-1.webp"),
        require("../../assets/blueprints/1/page-2.webp"),
        require("../../assets/blueprints/1/page-3.webp"),
        require("../../assets/blueprints/1/page-4.webp"),
        require("../../assets/blueprints/1/page-5.webp"),
      ],
    },
    {
      ref: "15",
      name: "Cal Poly Corporation Administration",
      pages: [
        require("../../assets/blueprints/15/page-1.webp"),
      ],
    },
  ],
  "way/45600405": [
    {
      ref: "8",
      name: "Bioresource and Agricultural Engineering",
      pages: [
        require("../../assets/blueprints/8/page-1.webp"),
        require("../../assets/blueprints/8/page-2.webp"),
      ],
    },
  ],
  "way/45600407": [
    {
      ref: "22",
      name: "English",
      pages: [
        require("../../assets/blueprints/22/page-1.webp"),
        require("../../assets/blueprints/22/page-2.webp"),
      ],
    },
    {
      ref: "10",
      name: "Alan A. Erhart Agriculture",
      pages: [
        require("../../assets/blueprints/10/page-1.webp"),
        require("../../assets/blueprints/10/page-2.webp"),
      ],
    },
  ],
  "way/45638391": [
    {
      ref: "11",
      name: "Agricultural Sciences",
      pages: [
        require("../../assets/blueprints/11/page-1.webp"),
        require("../../assets/blueprints/11/page-2.webp"),
        require("../../assets/blueprints/11/page-3.webp"),
      ],
    },
  ],
  "way/45638393": [
    {
      ref: "53",
      name: "Science North",
      pages: [
        require("../../assets/blueprints/53/page-1.webp"),
        require("../../assets/blueprints/53/page-2.webp"),
        require("../../assets/blueprints/53/page-3.webp"),
      ],
    },
  ],
  "way/45638394": [
    {
      ref: "47",
      name: "Faculty Offices North",
      pages: [
        require("../../assets/blueprints/47/page-1.webp"),
        require("../../assets/blueprints/47/page-2.webp"),
        require("../../assets/blueprints/47/page-3.webp"),
      ],
    },
  ],
  "way/45638400": [
    {
      ref: "52",
      name: "Science",
      pages: [
        require("../../assets/blueprints/52/page-1.webp"),
      ],
    },
  ],
  "way/45638401": [
    {
      ref: "65",
      name: "Julian A. Mcphee University Union",
      pages: [
        require("../../assets/blueprints/65/page-1.webp"),
        require("../../assets/blueprints/65/page-2.webp"),
        require("../../assets/blueprints/65/page-3.webp"),
        require("../../assets/blueprints/65/page-4.webp"),
        require("../../assets/blueprints/65/page-5.webp"),
      ],
    },
  ],
  "way/45638402": [
    {
      ref: "1",
      name: "Administration",
      pages: [
        require("../../assets/blueprints/1/page-1.webp"),
        require("../../assets/blueprints/1/page-2.webp"),
        require("../../assets/blueprints/1/page-3.webp"),
        require("../../assets/blueprints/1/page-4.webp"),
        require("../../assets/blueprints/1/page-5.webp"),
      ],
    },
  ],
  "way/45638403": [
    {
      ref: "33",
      name: "Clyde P. Fisher Science",
      pages: [
        require("../../assets/blueprints/33/page-1.webp"),
        require("../../assets/blueprints/33/page-2.webp"),
        require("../../assets/blueprints/33/page-3.webp"),
        require("../../assets/blueprints/33/page-4.webp"),
      ],
    },
  ],
  "way/45638408": [
    {
      ref: "5",
      name: "Architecture & Environmental Design",
      pages: [
        require("../../assets/blueprints/5/page-1.webp"),
        require("../../assets/blueprints/5/page-2.webp"),
        require("../../assets/blueprints/5/page-3.webp"),
        require("../../assets/blueprints/5/page-4.webp"),
      ],
    },
  ],
  "way/45644100": [
    {
      ref: "186",
      name: "Construction Innovations Center",
      pages: [
        require("../../assets/blueprints/186/page-1.webp"),
        require("../../assets/blueprints/186/page-2.webp"),
        require("../../assets/blueprints/186/page-3.webp"),
        require("../../assets/blueprints/186/page-4.webp"),
        require("../../assets/blueprints/186/page-5.webp"),
      ],
    },
  ],
  "way/45644213": [
    {
      ref: "31",
      name: "University Housing",
      pages: [
        require("../../assets/blueprints/31/page-1.webp"),
        require("../../assets/blueprints/31/page-2.webp"),
      ],
    },
  ],
  "way/45644222": [
    {
      ref: "13",
      name: "Engineering",
      pages: [
        require("../../assets/blueprints/13/page-1.webp"),
        require("../../assets/blueprints/13/page-2.webp"),
      ],
    },
  ],
  "way/486219813": [
    {
      ref: "6",
      name: "Christopher Cohan Center (1)",
      pages: [
        require("../../assets/blueprints/6/page-1.webp"),
        require("../../assets/blueprints/6/page-2.webp"),
        require("../../assets/blueprints/6/page-3.webp"),
        require("../../assets/blueprints/6/page-4.webp"),
        require("../../assets/blueprints/6/page-5.webp"),
      ],
    },
  ],
};

export function hasBlueprints(osmId: string | null | undefined): boolean {
  return !!osmId && osmId in BLUEPRINTS;
}

export const BLUEPRINT_OSM_IDS = new Set<string>(Object.keys(BLUEPRINTS));
