// AUTO-GENERATED by scripts/generate_blueprints.py — do not edit.

export interface BlueprintBuilding {
  ref: string;
  name: string;
  pages: number[];
}

export const BLUEPRINTS: Record<string, BlueprintBuilding[]> = {
  "way/1217465601": [
    {
      ref: "181",
      name: "William and Linda Frost Center for Research and Innovation",
      pages: [
        require("../../assets/blueprints/181/page-1.webp"),
        require("../../assets/blueprints/181/page-2.webp"),
        require("../../assets/blueprints/181/page-3.webp"),
        require("../../assets/blueprints/181/page-4.webp"),
        require("../../assets/blueprints/181/page-5.webp"),
      ],
    },
  ],
  "way/160415341": [
    {
      ref: "2",
      name: "Cotchett Education Building",
      pages: [
        require("../../assets/blueprints/2/page-1.webp"),
        require("../../assets/blueprints/2/page-2.webp"),
        require("../../assets/blueprints/2/page-3.webp"),
      ],
    },
  ],
  "way/160415342": [
    {
      ref: "3",
      name: "Business",
      pages: [
        require("../../assets/blueprints/3/page-1.webp"),
        require("../../assets/blueprints/3/page-2.webp"),
        require("../../assets/blueprints/3/page-3.webp"),
        require("../../assets/blueprints/3/page-4.webp"),
      ],
    },
  ],
  "way/322170587": [
    {
      ref: "180",
      name: "Warren J. Baker Center for Science and Mathematics",
      pages: [
        require("../../assets/blueprints/180/page-1.webp"),
        require("../../assets/blueprints/180/page-2.webp"),
        require("../../assets/blueprints/180/page-3.webp"),
        require("../../assets/blueprints/180/page-4.webp"),
        require("../../assets/blueprints/180/page-5.webp"),
        require("../../assets/blueprints/180/page-6.webp"),
        require("../../assets/blueprints/180/page-7.webp"),
      ],
    },
  ],
  "way/323359887": [
    {
      ref: "47",
      name: "Faculty Offices North",
      pages: [
        require("../../assets/blueprints/47/page-1.webp"),
        require("../../assets/blueprints/47/page-2.webp"),
        require("../../assets/blueprints/47/page-3.webp"),
      ],
    },
  ],
  "way/323359888": [
    {
      ref: "47",
      name: "Faculty Offices North",
      pages: [
        require("../../assets/blueprints/47/page-1.webp"),
        require("../../assets/blueprints/47/page-2.webp"),
        require("../../assets/blueprints/47/page-3.webp"),
      ],
    },
  ],
  "way/38899881": [
    {
      ref: "192",
      name: "Engineering Iv",
      pages: [
        require("../../assets/blueprints/192/page-1.webp"),
        require("../../assets/blueprints/192/page-2.webp"),
        require("../../assets/blueprints/192/page-3.webp"),
      ],
    },
  ],
  "way/38899884": [
    {
      ref: "7",
      name: "Advanced Technology Laboratories",
      pages: [
        require("../../assets/blueprints/7/page-1.webp"),
      ],
    },
  ],
  "way/45600389": [
    {
      ref: "38",
      name: "Mathematics and Science",
      pages: [
        require("../../assets/blueprints/38/page-1.webp"),
        require("../../assets/blueprints/38/page-2.webp"),
      ],
    },
  ],
  "way/45600390": [
    {
      ref: "10",
      name: "Alan A. Erhart Agriculture",
      pages: [
        require("../../assets/blueprints/10/page-1.webp"),
        require("../../assets/blueprints/10/page-2.webp"),
      ],
    },
    {
      ref: "22",
      name: "English",
      pages: [
        require("../../assets/blueprints/22/page-1.webp"),
        require("../../assets/blueprints/22/page-2.webp"),
      ],
    },
  ],
  "way/45600403": [
    {
      ref: "1",
      name: "Administration",
      pages: [
        require("../../assets/blueprints/1/page-1.webp"),
        require("../../assets/blueprints/1/page-2.webp"),
        require("../../assets/blueprints/1/page-3.webp"),
        require("../../assets/blueprints/1/page-4.webp"),
        require("../../assets/blueprints/1/page-5.webp"),
      ],
    },
  ],
  "way/45600407": [
    {
      ref: "10",
      name: "Alan A. Erhart Agriculture",
      pages: [
        require("../../assets/blueprints/10/page-1.webp"),
        require("../../assets/blueprints/10/page-2.webp"),
      ],
    },
    {
      ref: "22",
      name: "English",
      pages: [
        require("../../assets/blueprints/22/page-1.webp"),
        require("../../assets/blueprints/22/page-2.webp"),
      ],
    },
  ],
  "way/45638391": [
    {
      ref: "11",
      name: "Agricultural Sciences",
      pages: [
        require("../../assets/blueprints/11/page-1.webp"),
        require("../../assets/blueprints/11/page-2.webp"),
        require("../../assets/blueprints/11/page-3.webp"),
      ],
    },
  ],
  "way/45638393": [
    {
      ref: "53",
      name: "Science North",
      pages: [
        require("../../assets/blueprints/53/page-1.webp"),
        require("../../assets/blueprints/53/page-2.webp"),
        require("../../assets/blueprints/53/page-3.webp"),
      ],
    },
  ],
  "way/45638394": [
    {
      ref: "47",
      name: "Faculty Offices North",
      pages: [
        require("../../assets/blueprints/47/page-1.webp"),
        require("../../assets/blueprints/47/page-2.webp"),
        require("../../assets/blueprints/47/page-3.webp"),
      ],
    },
  ],
  "way/45638400": [
    {
      ref: "52",
      name: "Science",
      pages: [
        require("../../assets/blueprints/52/page-1.webp"),
      ],
    },
  ],
  "way/45638402": [
    {
      ref: "1",
      name: "Administration",
      pages: [
        require("../../assets/blueprints/1/page-1.webp"),
        require("../../assets/blueprints/1/page-2.webp"),
        require("../../assets/blueprints/1/page-3.webp"),
        require("../../assets/blueprints/1/page-4.webp"),
        require("../../assets/blueprints/1/page-5.webp"),
      ],
    },
  ],
  "way/45638403": [
    {
      ref: "33",
      name: "Clyde P. Fisher Science",
      pages: [
        require("../../assets/blueprints/33/page-1.webp"),
        require("../../assets/blueprints/33/page-2.webp"),
        require("../../assets/blueprints/33/page-3.webp"),
        require("../../assets/blueprints/33/page-4.webp"),
      ],
    },
  ],
};

export function hasBlueprints(osmId: string | null | undefined): boolean {
  return !!osmId && osmId in BLUEPRINTS;
}

export const BLUEPRINT_OSM_IDS = new Set<string>(Object.keys(BLUEPRINTS));
